# Generated by Django 2.2.3 on 2019-08-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='BlogPost',
        ),
    ]
